USE [master]
GO

CREATE DATABASE [PERCIVALDI_DB]
GO


USE [PERCIVALDI_DB]
GO

CREATE TABLE USUARIOS(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	ACCESS VARCHAR(30) NOT NULL,
	DEPID INT NOT NULL FOREIGN KEY REFERENCES DEPARTAMENTOS(IDDEP),
	MAIL VARCHAR(30) NOT NULL,
	)

CREATE TABLE DEPARTAMENTOS(
	IDDEP INT IDENTITY(1,1) PRIMARY KEY,
	NOMBREDEPTO VARCHAR(30) NOT NULL,
)

CREATE TABLE ROLES(
	IDROL INT IDENTITY(1,1) PRIMARY KEY,
	NOMBREROL VARCHAR(30) NOT NULL,
)

USE [PERCIVALDI_DB]
GO

CREATE PROCEDURE SP_NEWUSR(
@nombre VARCHAR(30),
@apellido VARCHAR(30),
@access VARCHAR(30),
@depto int,
@mail VARCHAR(30)
)
AS
BEGIN
	INSERT INTO USUARIOS(NOMBRE,APELLIDO,ACCESS,DEPID,MAIL)
	VALUES (@nombre,@apellido,@access,@depto,@mail)
END
GO

USE [PERCIVALDI_DB]
GO

CREATE PROCEDURE SP_NEWDEPTO(
@nombreDepto VARCHAR(30)
)
AS
BEGIN
	INSERT INTO DEPARTAMENTOS(NOMBREDEPTO)
	VALUES(@nombreDepto)
END
GO

USE [PERCIVALDI_DB]
GO

EXEC SP_NEWDEPTO 'Administración y Finanzas'
EXEC SP_NEWDEPTO 'Recursos Humanos'
EXEC SP_NEWDEPTO 'Ventas'
EXEC SP_NEWDEPTO 'Servicio Técnico'
EXEC SP_NEWDEPTO 'Instalaciones'
EXEC SP_NEWDEPTO 'Ingenieria'
EXEC SP_NEWDEPTO 'Operaciones'
GO

USE [PERCIVALDI_DB]
GO
EXEC SP_NEWUSR 'Mario','Percivaldi','cadillac',1,'percivaldi.mario@gmail.com'

